[webhook]
enabled = false
url = "https://discord.com/api/webhooks/.../..."
show_host_port = true

[bind]
addr = "0.0.0.0"
ports = [25565, 25566]

[server]
disconnect_message = "Get baited!"
description = "GeorgeNotFound private recording server"
online_players = 2
max_players = 20

[randomize]
# Whether to randomize the player sample
# Characters used: A-Z a-z 0-9 _
# The players defined in the config will be added before the random players
randomize_players = false
# The length of the names of random players
randomize_players_name_len = 5
# How many random players to add to the sample
# Note: The packet can be 32767 bytes at most
randomize_players_len = 100
# Whether to randomize online players and max players to any number between -2,147,483,648 and 2,147,483,647
randomize_online_max = false

[[player]]
name = "GeorgeNotFound"
uuid = "bd3dd5a4-0438-4699-b2fd-36f518154b41"

[[player]]
name = "Dream"
uuid = "ec70bcaf-702f-4bb8-b48d-276fa52a780c"