[bind]
addr = "0.0.0.0"
port = 25565

[server]
description = "GeorgeNotFound private recording server"
online_players = 1
max_players = 20

[[player]]
name = "GeorgeNotFound"
uuid = "bd3dd5a4-0438-4699-b2fd-36f518154b41"